### PR TITLE
Align API with contracts v1.4.2

### LINKED ISSUE #90: [BUG] AuthController.registerUser returns 201 instead of 204
### Description
The `AuthController.registerUser` method currently returns `201 Created` upon successful registration. However, the OpenAPI specification (`budget-buddy-contracts/specs/openapi.yaml`) defines the successful response for `/v1/auth/register` as `204 No Content`.

### Current Implementation
In `src/main/java/com/budget/buddy/budget_buddy_api/security/auth/AuthController.java`:
```java
@Override
public ResponseEntity<Void> registerUser(RegisterRequest registerRequest) {
  authService.register(registerRequest);
  return ResponseEntity.status(HttpStatus.CREATED).build();
}
```

### Expected Behavior
The method should return `204 No Content` to match the contract:
```java
@Override
public ResponseEntity<Void> registerUser(RegisterRequest registerRequest) {
  authService.register(registerRequest);
  return ResponseEntity.noContent().build();
}
```

### LINKED ISSUE #91: [BUG] TransactionController parameter name 'order' instead of 'sort'
### Description
The `TransactionController.listTransactions` method uses `order` as the query parameter name for sorting. However, the OpenAPI specification (`budget-buddy-contracts/specs/openapi.yaml`) defines the query parameter as `sort`.

### Current Implementation
In `src/main/java/com/budget/buddy/budget_buddy_api/transaction/TransactionController.java`:
```java
@Override
public ResponseEntity<PaginatedTransactions> listTransactions(
    Integer limit,
    Integer offset,
    UUID categoryId,
    LocalDate start,
    LocalDate end,
    String order // Incorrect parameter name
) {
  var sort = Direction.fromOptionalString(order)
      .map(direction -> Sort.by(direction, "date"))
      .orElse(DEFAULT_SORT);
  // ...
}
```

### Expected Behavior
The method should use `sort` to match the OpenAPI specification:
```java
@Override
public ResponseEntity<PaginatedTransactions> listTransactions(
    Integer limit,
    Integer offset,
    UUID categoryId,
    LocalDate start,
    LocalDate end,
    String sort // Should match OpenAPI parameter name
) {
  // Use sort here
}
```

### LINKED ISSUE #93: [BUG] TransactionEntity amount field type mismatch (Integer vs Long)
### Description
The `TransactionEntity` defines the `amount` field as `Integer`. However, the OpenAPI specification (`budget-buddy-contracts/specs/openapi.yaml`) defines the `amount` property as `integer` with `format: int64`, which maps to a `Long` in Java.

### Current Implementation
In `src/main/java/com/budget/buddy/budget_buddy_api/transaction/TransactionEntity.java`:
```java
@Column("amount")
private Integer amount; // Incorrect type
```

### Expected Behavior
The field should be of type `Long` to match the contract:
```java
@Column("amount")
private Long amount; // Should match OpenAPI int64
```

### PR DESCRIPTION
**Pull request by glebremniov**
This PR aligns the API implementation with the latest version of `budget-buddy-contracts` (v1.4.2).

### Changes
- **Dependency Update:** Upgraded `budget-buddy-contracts` to `1.4.2`.
- **Transactions:**
  - Changed `amount` field from `Integer` to `Long` in `TransactionEntity` and all related layers to support larger values and match the contract.
  - Added Liquibase migration (`007-transaction-amount-bigint.sql`) to update the `amount` column type in the database.
  - Renamed `listTransactions` parameter `order` to `sort` to match the OpenAPI specification.
- **Authentication:**
  - Refactored `AuthController.registerUser` to return `204 No Content` instead of `201 Created` for compliance with the contract.
- **Tests:**
  - Updated integration and unit tests to reflect the new amount type and status codes.

### Closes
- Closes #90
- Closes #91
- Closes #93

### CODE REVIEW

File: src/integrationTest/java/com/budget/buddy/budget_buddy_api/security/auth/AuthIntegrationTest.java [hunk 1]
```diff
@@ -72,7 +72,7 @@ void should_RegisterUser_When_ValidRequest() {
       // Then
       assertThat(exchange)
           .as("Registration should return 201 Created")
```
Comment (glebremniov) [inline src/integrationTest/java/com/budget/buddy/budget_buddy_api/security/auth/AuthIntegrationTest.java]: **Bug:** Stale assertion message — says `"Registration should return 201 Created"` but the assertion on the next line now checks for `NO_CONTENT` (204). When this test fails in the future, the message will actively mislead. Should be `"Registration should return 204 No Content"`.

File: src/integrationTest/java/com/budget/buddy/budget_buddy_api/BaseMvcIntegrationTest.java [hunk 2]
```diff
@@ -41,7 +40,7 @@ protected void register(String username, String password) {
         .content(json(new RegisterRequest().username(username).password(password)))
         .exchange();
 
-    assertThat(exchange).hasStatus(HttpStatus.CREATED);
+    assertThat(exchange).hasStatus2xxSuccessful();
```
Comment (glebremniov) [inline src/integrationTest/java/com/budget/buddy/budget_buddy_api/BaseMvcIntegrationTest.java:43]: **Nit:** `hasStatus2xxSuccessful()` is weaker than the previous `hasStatus(HttpStatus.CREATED)`. Since `register` now returns 204, this should be `hasStatus(HttpStatus.NO_CONTENT)` — equally specific, and consistent with the explicit assertion in `AuthIntegrationTest`.

File: src/integrationTest/java/com/budget/buddy/budget_buddy_api/BaseMvcIntegrationTest.java [hunk 3]
```diff
@@ -50,7 +49,7 @@ protected AuthToken login(String username, String password) throws Exception {
         .content(json(new LoginRequest().username(username).password(password)))
         .exchange();
 
-    assertThat(exchange).hasStatus(HttpStatus.OK);
+    assertThat(exchange).hasStatus2xxSuccessful();
```
Comment (glebremniov) [inline src/integrationTest/java/com/budget/buddy/budget_buddy_api/BaseMvcIntegrationTest.java:52]: **Nit:** Login is unchanged and still returns 200 OK, but the assertion was softened to `hasStatus2xxSuccessful()`. This looks like an unintentional casualty of the registration change. Restore to `hasStatus(HttpStatus.OK)` to keep the helper precise.

**Review by glebremniov — COMMENTED** [review]
This PR cleanly aligns the implementation with contracts v1.4.2. Changes are focused and well-scoped: `Integer→Long` type migration (entity, mapper, tests, DB migration), `order→sort` rename in `listTransactions`, and `register` returning 204 instead of 201. The Liquibase migration includes a rollback — good. Three minor test-quality issues noted below (2 nits, 1 bug). No correctness concerns in production code.

File: src/integrationTest/java/com/budget/buddy/budget_buddy_api/security/auth/AuthIntegrationTest.java (hunk 1 above)
Comment (glebremniov) [reply src/integrationTest/java/com/budget/buddy/budget_buddy_api/security/auth/AuthIntegrationTest.java]: Updated

File: src/integrationTest/java/com/budget/buddy/budget_buddy_api/BaseMvcIntegrationTest.java (hunk 2 above)
Comment (glebremniov) [reply src/integrationTest/java/com/budget/buddy/budget_buddy_api/BaseMvcIntegrationTest.java:43]: Do we need to care about the exact status in a helper method? We have a separate `AuthIntegrationTest` that verifies this path.

File: src/integrationTest/java/com/budget/buddy/budget_buddy_api/BaseMvcIntegrationTest.java (hunk 3 above)
Comment (glebremniov) [reply src/integrationTest/java/com/budget/buddy/budget_buddy_api/BaseMvcIntegrationTest.java:52]: Do we need to care about the exact status in a helper method? We have a separate `AuthIntegrationTest` that verifies this path.

File: src/integrationTest/java/com/budget/buddy/budget_buddy_api/security/auth/AuthIntegrationTest.java (hunk 1 above)
Comment (glebremniov) [reply src/integrationTest/java/com/budget/buddy/budget_buddy_api/security/auth/AuthIntegrationTest.java]: Addressed — resolving. ✓

File: src/integrationTest/java/com/budget/buddy/budget_buddy_api/BaseMvcIntegrationTest.java (hunk 2 above)
Comment (glebremniov) [reply src/integrationTest/java/com/budget/buddy/budget_buddy_api/BaseMvcIntegrationTest.java:43]: Fair point — `AuthIntegrationTest.Register.should_RegisterUser_When_ValidRequest` has an explicit `hasStatus(NO_CONTENT)` check, so the helper using `hasStatus2xxSuccessful()` is redundant rather than a gap. Accepting this.

File: src/integrationTest/java/com/budget/buddy/budget_buddy_api/BaseMvcIntegrationTest.java (hunk 3 above)
Comment (glebremniov) [reply src/integrationTest/java/com/budget/buddy/budget_buddy_api/BaseMvcIntegrationTest.java:52]: The same reasoning doesn't fully apply here: `Login.should_ReturnTokens_When_ValidCredentials` delegates to the helper and never explicitly asserts `hasStatus(HttpStatus.OK)` anywhere — so the loose check means a login returning 201 or 204 would silently pass. Keeping this open.

**Review by glebremniov — COMMENTED** [review]
**Re-review summary**

**Addressed (2/3):**
- ✓ Stale comment fixed: `AuthIntegrationTest` now says "Registration should return 204 No Content" — resolved.
- ✓ `register()` helper looseness accepted: `AuthIntegrationTest.Register.should_RegisterUser_When_ValidRequest` has an explicit `hasStatus(NO_CONTENT)` check, so the helper's `hasStatus2xxSuccessful()` is covered — resolved.

**Still open (1):**
- `login()` helper in `BaseMvcIntegrationTest` still uses `hasStatus2xxSuccessful()`. Unlike the register case, `Login.should_ReturnTokens_When_ValidCredentials` delegates to this helper and there is no other test explicitly asserting `hasStatus(HttpStatus.OK)` for the success path. A login returning 201 or 204 would silently pass. Please either restore `hasStatus(HttpStatus.OK)` in the helper, or add a dedicated assertion in `AuthIntegrationTest.Login.should_ReturnTokens_When_ValidCredentials`.

No new issues found in the updated diff.

File: src/integrationTest/java/com/budget/buddy/budget_buddy_api/BaseMvcIntegrationTest.java (hunk 3 above)
Comment (glebremniov) [reply src/integrationTest/java/com/budget/buddy/budget_buddy_api/BaseMvcIntegrationTest.java:52]: Updated `authIntegrationTest`

Comment (glebremniov) [reply src/integrationTest/java/com/budget/buddy/budget_buddy_api/BaseMvcIntegrationTest.java:52]: Addressed — resolving. ✓ Overriding `login()` in `AuthIntegrationTest` is a clean solution: the base helper stays loose for other subclasses, while auth tests get the precise `hasStatus(HttpStatus.OK)` check.

**Review by glebremniov — COMMENTED** [review]
**Re-review summary — all clear**

All 3 prior comments resolved:
- ✓ Stale `as()` message updated to "204 No Content"
- ✓ `register()` helper looseness accepted (covered by explicit assertion in `AuthIntegrationTest.Register`)
- ✓ Login status gap closed by overriding `login()` in `AuthIntegrationTest` with `hasStatus(HttpStatus.OK)` — clean approach that keeps the base helper flexible for other subclasses

No new issues. LGTM.
